[build]
  base = "frontend" # Assuming your frontend code is in the "frontend" directory
  command = "vite build"
  publish = "frontend/build" # Assuming the build output is in "frontend/build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_ENV = "production"
  RUBY_VERSION = 2.7.2
  BASE_URL = "https://brain-boost.onrender.com"