[build]
  base = "frontend"
  command = "vite build"
  publish = "frontend/dist" # Ensure this matches Vite's output directory

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_ENV = "production"
  BASE_URL = "https://brain-boost.onrender.com"
